services:
  rtsp_server:
    image: bluenviron/mediamtx:latest
    container_name: rtsp_server
    ports:
      - "8554:8554"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    restart: unless-stopped
  cam1:
    build: .
    container_name: cam1
    depends_on:
      - rtsp_server
    environment:
      - VIDEO_FILE=${CAM1_VIDEO_FILE:-/videos/cam1.mp4}
      - RTSP_URL=${CAM1_RTSP_URL:-rtsp://rtsp_server:8554/cam1}
    volumes:
      - ./videos:/videos
    restart: unless-stopped

  cam2:
    build: .
    container_name: cam2
    depends_on:
      - rtsp_server
    environment:
      - VIDEO_FILE=${CAM2_VIDEO_FILE:-/videos/cam2.mp4}
      - RTSP_URL=${CAM2_RTSP_URL:-rtsp://rtsp_server:8554/cam2}
    volumes:
      - ./videos:/videos
    restart: unless-stopped

  # cam3:
  #   build: .
  #   container_name: cam3
  #   depends_on:
  #     - rtsp_server
  #   environment:
  #     - VIDEO_FILE=/videos/video_in_W.mp4
  #     - RTSP_URL=rtsp://rtsp_server:8554/cam3
  #   volumes:
  #     - ./videos:/videos
  #   restart: unless-stopped
